In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re
import requests
import pandas as pd
import time

In [2]:
URL = 'https://www.scrapethissite.com/pages/forms/'

page = requests.get(URL)
html = page.content
soup = BeautifulSoup(html, "html.parser")

In [3]:
table = soup.find("table",class_="table")

In [5]:
columns = soup.find_all('th')

titles = ()

def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '',text)

for i in columns:
    x = remove_html_tags(str(i))
    l = list(titles)
    if x != "None":
        t = x.replace('\n', '')
        l.append(t)
        titles = tuple(l)

In [6]:
df = pd.DataFrame(columns=['Team Name','Year','Wins','Losses','OT Losses','Win %','Goals For','Goals Against','+/-'])

In [7]:
for r in table.find_all('tr'):
     cols = r.find_all('td')
     
     
     if (cols != []):
         name = remove_html_tags(str(cols[0])).replace('\n','').replace(' ','')
         year = remove_html_tags(str(cols[1])).replace('\n','')
         wins = remove_html_tags(str(cols[2])).replace('\n','')
         losses = remove_html_tags(str(cols[3])).replace('\n','')
         ot = remove_html_tags(str(cols[4])).replace('\n','')
         winPerc = remove_html_tags(str(cols[5])).replace('\n','')
         gf = remove_html_tags(str(cols[6])).replace('\n','')
         ga = remove_html_tags(str(cols[7])).replace('\n','')
         over_under = remove_html_tags(str(cols[8])).replace('\n','')
         
         df = pd.concat([df, pd.DataFrame.from_records([{'Team Name': name, 'Year': year, 'Wins': wins, 'Losses': losses, 'OT Losses': ot, 'Win %': winPerc, 'Goals For': gf, 'Goals Against': ga, '+/-':over_under}])], ignore_index=True)

In [8]:
df.to_csv('test.csv')

In [14]:

#new = df[(df['Win %'].astype(float) >= 0.50).all()]

df['Win %'].astype(float)

df['Win %'].dtype


df.loc[(df['Win %'].astype(float) >= 0.50) & (df['Goals Against'].astype(int) >= 300)]

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For,Goals Against,+/-
14,PittsburghPenguins,1990 ...,41 ...,33 ...,,0.512 ...,342 ...,305 ...,37 ...

In [17]:
df.sort_values(by='Goals Against', ascending=False)

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For,Goals Against,+/-
15,QuebecNordiques,1990 ...,16 ...,50 ...,,0.2 ...,236 ...,354 ...,-118 ...
17,TorontoMapleLeafs,1990 ...,23 ...,46 ...,,0.287 ...,241 ...,318 ...,-77 ...
18,VancouverCanucks,1990 ...,28 ...,43 ...,,0.35 ...,243 ...,315 ...,-72 ...
23,CalgaryFlames,1991 ...,31 ...,37 ...,,0.388 ...,296 ...,305 ...,-9 ...
14,PittsburghPenguins,1990 ...,41 ...,33 ...,,0.512 ...,342 ...,305 ...,37 ...
22,BuffaloSabres,1991 ...,31 ...,37 ...,,0.388 ...,289 ...,299 ...,-10 ...
4,DetroitRedWings,1990 ...,34 ...,38 ...,,0.425 ...,273 ...,298 ...,-25 ...
11,NewYorkIslanders,1990 ...,25 ...,45 ...,,0.312 ...,223 ...,290 ...,-67 ...
20,WinnipegJets,1990 ...,26 ...,43 ...,,0.325 ...,260 ...,288 ...,-28 ...
1,BuffaloSabres,1990 ...,31 ...,30 ...,,0.388 ...,292 ...,278 ...,14 ...
6,HartfordWhalers,1990 ...,31 ...,38 ...,,0.388 ...,238 ...,276 ...,-38 ...
21,BostonBruins,1991 ...,36 ...,32 ...,,0.45 ...,270 ...,275 ...,-5 ...
5,EdmontonOilers,1990 ...,37 ...,37 ...,,0.463 ...,272 ...,272 ...,0 ...
13,PhiladelphiaFlyers,1990 ...,33 ...,37 ...,,0.412 ...,252 ...,267 ...,-15 ...
8,MinnesotaNorthStars,1990 ...,27 ...,39 ...,,0.338 ...,256 ...,266 ...,-10 ...
12,NewYorkRangers,1990 ...,36 ...,31 ...,,0.45 ...,297 ...,265 ...,32 ...
0,BostonBruins,1990 ...,44 ...,24 ...,,0.55 ...,299 ...,264 ...,35 ...
10,NewJerseyDevils,1990 ...,32 ...,33 ...,,0.4 ...,272 ...,264 ...,8 ...
2,CalgaryFlames,1990 ...,46 ...,26 ...,,0.575 ...,344 ...,263 ...,81 ...
19,WashingtonCapitals,1990 ...,37 ...,36 ...,,0.463 ...,258 ...,258 ...,0 ...
7,LosAngelesKings,1990 ...,46 ...,24 ...,,0.575 ...,340 ...,254 ...,86 ...
16,St.LouisBlues,1990 ...,47 ...,22 ...,,0.588 ...,310 ...,250 ...,60 ...
9,MontrealCanadiens,1990 ...,39 ...,30 ...,,0.487 ...,273 ...,249 ...,24 ...
24,ChicagoBlackhawks,1991 ...,36 ...,29 ...,,0.45 ...,257 ...,236 ...,21 ...
3,ChicagoBlackhawks,1990 ...,49 ...,23 ...,,0.613 ...,284 ...,211 ...,73 ...